import spacy
nlp = spacy.load("hu_core_news_lg")
doc = nlp("A Fidesz által támogatott induló Facebook-profilja megszűnt, a Fidesz Jászság oldalán pedig több napnyi posztot töröltek, miután a Közösen Jászberényért színeiben induló jobbikos polgármesterjelölt több mint kétszer annyi szavazatot kapott a jászberényi időközi önkormányzati választáson, mint a Fidesz-KDNP által támogatott, ám függetlenként indult Besenyi Orsolya.Besenyi Orsolya, aki civilben a helyi kórház orvosigazgatója, még a 100 százalékos feldolgozottság előtt törölte a politikusi Facebook-oldalát. Kollégáink figyeltek fel rá, hogy az oldal vasárnap este már nem volt elérhető, hétfő délelőtt ez a felirat fogadja az oldal látogatóit:„Ez a tartalom jelenleg nem érhető el. Ez általában olyankor fordul elő, amikor a tulajdonosa csak kisebb csoportnyi emberrel osztotta meg, megváltoztatta a láthatóságát, vagy törölték.”Besenyi Orsolya hirdetései novembertől futottak a Facebookon, a politikus 667 ezer forintot hirdetett el, amiből 140 hirdetésre futotta – derül ki a Facebook Ad Library nevű felületéről, amely mindenki számára elérhetően tartja nyilván a politikai-közéleti hirdetések részleteit.Nemcsak a jelölt oldaláról tűntek el tartalmak; a Fidesz Jászság Facebook-oldalán az elmúlt napokra visszamenőleg minden posztot töröltek. A „hajrá Orsi”-s kommentek ugyanakkor megmaradtak a törölt posztok alatt.Így néz ki hétfő délelőtt a Facebook-oldal:   Pedig rendesen bevetették a közösségi médiát a Fidesz által támogatott induló győzelméért: novemberben Jászberény többet érdemel néven egy olyan Facebook-oldal is elstartolt, amelyen 600 ezret költöttek hirdetésre, és ahol egyebek mellett Márky-Zay Péter dollárbutykosokkal kitömött embereivel riogatták, valamint a Pesti srácok cikkeivel szórakoztatták 522 követőjüket (összehasonlításképp: Jászberényben 26 500 ember lakik). A hirdetésnél megadott adatok a Jászságjava-oldal egyik emailcímére mutatnak.Vasárnap kétharmados győzelmet aratott az ellenzék Jászberényben. A vártnál jóval simábban nyert Budai Lóránt ellenzéki polgármesterjelölt a vasárnapi jászberényi időközi önkormányzati választáson, és tízből tíz egyéni körzetben is az ellenzéki szövetség, a Közösen Jászberényért képviselőjelöltje győzött. A szövetségben a DK kivételével minden ellenzéki párt részt vett.A jászberényi polgármester-választás végeredménye:Budai Lóránt (Közösen Jászberényért): 8267 (67,24%)Besenyi Orsolya (a Fidesz–KDNP által támogatott független): 3671 (29,86%)Nagy Tímea (független): 185 (1,5%)László Péter (Mi Hazánk): 172 (1,4%)Az újonnan felálló képviselő-testületben a polgármesterrel együtt 11 tagja lesz a Közösen Jászberényért egyesületnek, a Fidesz–KDNP pedig négy helyet szerzett kompenzációs listáról. A Mi Hazánk Mozgalom nem jutott be a testületbe.A jászberényi választás előzményeiről és a kampányról a héten helyszíni riportban jelentkeztünk.")

output_text = ""
for token in doc:
    if token.ent_type_ != "":
        output_text += ' <span class="{}">{}</span> '.format(token.ent_type_, token.text)
    else:
        output_text += " " + token.text

print(output_text)

